/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotStatus.h>

@class NSDate, PTHTweetbotUser, NSString;

@interface _PTHTweetbotDisplaySettingsStatus : PTHTweetbotStatus {

	NSDate* createdAt;
	PTHTweetbotUser* user;

}

@property (nonatomic,retain) NSDate * createdAt; 
@property (nonatomic,copy) NSString * text; 
@property (nonatomic,retain) PTHTweetbotUser * user; 
-(PTHTweetbotUser *)user;
-(void)setUser:(PTHTweetbotUser *)arg1 ;
-(void)setCreatedAt:(NSDate *)arg1 ;
-(NSDate *)createdAt;
@end

