/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <UIKit/UIControl.h>

@class UIImage, PTHProgressView, UIImageView, PTHTweetbotMedium;

@interface _PTHTweetbotStatusDetailMediumView : UIControl {

	UIImage* _image;
	BOOL _loading;
	unsigned long long _loadCount;
	PTHProgressView* _progressView;
	UIImageView* _imageView;
	CGSize _requestedImageSize;
	PTHTweetbotMedium* _medium;

}

@property (nonatomic,readonly) PTHTweetbotMedium * medium;              //@synthesize medium=_medium - In the implementation block
@property (nonatomic,readonly) CGRect imageBounds; 
-(id)initWithMedium:(id)arg1 ;
-(void)_loadImageIfNeeded;
-(void)setFrame:(CGRect)arg1 ;
-(void)setBounds:(CGRect)arg1 ;
-(PTHTweetbotMedium *)medium;
-(CGRect)imageBounds;
@end

