/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class PTHTweetbotAccount, PTHTweetbotOAuthURLRequest;

@interface _PTHTweetbotAccountRequestOperation : NSOperation {

	unsigned long long _retryCount;
	BOOL _executing;
	BOOL _finished;
	PTHTweetbotAccount* _account;
	PTHTweetbotOAuthURLRequest* _request;
	/*^block*/id _progressBlock;
	/*^block*/id _responseBlock;

}

@property (nonatomic,retain) PTHTweetbotAccount * account;                      //@synthesize account=_account - In the implementation block
@property (nonatomic,retain) PTHTweetbotOAuthURLRequest * request;              //@synthesize request=_request - In the implementation block
@property (nonatomic,copy) id progressBlock;                                    //@synthesize progressBlock=_progressBlock - In the implementation block
@property (nonatomic,copy) id responseBlock;                                    //@synthesize responseBlock=_responseBlock - In the implementation block
@property (getter=isExecuting) BOOL executing;                                  //@synthesize executing=_executing - In the implementation block
@property (getter=isFinished) BOOL finished;                                    //@synthesize finished=_finished - In the implementation block
-(BOOL)isAsynchronous;
-(id)responseBlock;
-(PTHTweetbotOAuthURLRequest *)request;
-(void)start;
-(BOOL)isFinished;
-(BOOL)isExecuting;
-(void)setExecuting:(BOOL)arg1 ;
-(void)setRequest:(PTHTweetbotOAuthURLRequest *)arg1 ;
-(void)setFinished:(BOOL)arg1 ;
-(id)progressBlock;
-(void)setProgressBlock:(id)arg1 ;
-(void)sendRequest;
-(void)setResponseBlock:(id)arg1 ;
-(void)setAccount:(PTHTweetbotAccount *)arg1 ;
-(PTHTweetbotAccount *)account;
@end

