/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <PTHCommon/PTHShapeView.h>

@class UIVisualEffectView, UIImageView, UITabBarItem, UIViewController;

@interface _PTHTweetbotAccountReoderTabButton : PTHShapeView {

	UIVisualEffectView* _effectView;
	UIImageView* _imageView;
	BOOL _highlighted;
	UITabBarItem* _item;
	UIViewController* _viewController;

}

@property (nonatomic,retain) UITabBarItem * item;                                   //@synthesize item=_item - In the implementation block
@property (assign,nonatomic,__weak) UIViewController * viewController;              //@synthesize viewController=_viewController - In the implementation block
-(void)layoutSubviews;
-(UITabBarItem *)item;
-(void)setHighlighted:(BOOL)arg1 ;
-(void)setViewController:(UIViewController *)arg1 ;
-(UIViewController *)viewController;
-(BOOL)highlighted;
-(void)setItem:(UITabBarItem *)arg1 ;
-(id)initWithViewController:(id)arg1 ;
@end

