/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <UIKit/UIControl.h>

@class UIImageView, UILabel;

@interface _PTHTweetbotSetupPickerItemView : UIControl {

	UIImageView* _checkmarkView;
	UILabel* _titleLabel;
	double _fontSize;

}

@property (nonatomic,readonly) UIImageView * checkmarkView;              //@synthesize checkmarkView=_checkmarkView - In the implementation block
@property (nonatomic,readonly) UILabel * titleLabel;                     //@synthesize titleLabel=_titleLabel - In the implementation block
@property (assign,nonatomic) double fontSize;                            //@synthesize fontSize=_fontSize - In the implementation block
-(void)_updateFont;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)tintColorDidChange;
-(id)initWithTitle:(id)arg1 ;
-(void)setHighlighted:(BOOL)arg1 ;
-(UILabel *)titleLabel;
-(void)setSelected:(BOOL)arg1 ;
-(void)setFontSize:(double)arg1 ;
-(UIImageView *)checkmarkView;
-(double)fontSize;
@end

