/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotAccountTabBarItemView.h>

@class UIImageView;

@interface _PTHTweetbotAccountCompactTabBarItemView : PTHTweetbotAccountTabBarItemView {

	UIImageView* _arrowsView;
	BOOL _vertical;

}

@property (assign,getter=hasArrows,nonatomic) BOOL arrows; 
@property (assign,getter=isVertical,nonatomic) BOOL vertical;              //@synthesize vertical=_vertical - In the implementation block
-(BOOL)hasArrows;
-(void)setArrows:(BOOL)arg1 ;
-(void)layoutSubviews;
-(BOOL)isVertical;
-(void)setVertical:(BOOL)arg1 ;
@end

