/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <UIKit/UIControl.h>

@class PTHTweetbotEntity, UIViewController;

@interface _PTHTweetbotUserProfilePhotosBlockView : UIControl {

	PTHTweetbotEntity* _entity;
	UIViewController* _controller;

}

@property (nonatomic,retain) PTHTweetbotEntity * entity;                        //@synthesize entity=_entity - In the implementation block
@property (assign,nonatomic,__weak) UIViewController * controller;              //@synthesize controller=_controller - In the implementation block
-(void)_showMedia;
-(id)initWithEntity:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(UIViewController *)controller;
-(void)setController:(UIViewController *)arg1 ;
-(PTHTweetbotEntity *)entity;
-(void)setEntity:(PTHTweetbotEntity *)arg1 ;
@end

