/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


#import <Tweetbot/Tweetbot-Structs.h>
@class UIView;

@interface _PTHTweetbotPostToolbarItem : NSObject {

	UIView* _view;
	id _result;
	CGRect _frame;

}

@property (nonatomic,retain) UIView * view;              //@synthesize view=_view - In the implementation block
@property (nonatomic,retain) id result;                  //@synthesize result=_result - In the implementation block
@property (assign,nonatomic) CGRect frame;               //@synthesize frame=_frame - In the implementation block
-(void)setFrame:(CGRect)arg1 ;
-(CGRect)frame;
-(BOOL)isEqual:(id)arg1 ;
-(id)description;
-(UIView *)view;
-(void)setView:(UIView *)arg1 ;
-(id)result;
-(void)setResult:(id)arg1 ;
@end

