/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <Tweetbot/PTHTweetbotStatusDetailChildController.h>
#import <UIKit/UIScrollViewDelegate.h>

@class NSArray, UIScrollView, UIPageControl, NSMutableArray, NSLayoutConstraint, NSString;

@interface PTHTweetbotStatusDetailMediaController : PTHTweetbotStatusDetailChildController <UIScrollViewDelegate> {

	NSArray* _loadedMedia;
	BOOL _isLoaded;
	UIScrollView* _scrollView;
	UIPageControl* _pageControl;
	NSArray* _mediaViews;
	NSMutableArray* _mediaViewsConstraints;
	NSLayoutConstraint* _heightConstraint;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)statusWasUpdated;
-(void)_loadMedia;
-(void)_presentMedium:(id)arg1 ;
-(void)_pageControlChanged;
-(void)previewingStatusDidChange;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
@end

