/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSDate, NSTimer, PTHTweetbotAccount, CKServerChangeToken, CKRecordZone, NSArray, NSString;

@interface PTHTweetbotStatusFilterController : NSObject {

	BOOL _hasLoaded;
	NSMutableArray* _filters;
	NSMutableDictionary* _recordsByID;
	NSMutableSet* _deletedRecordIDs;
	NSMutableSet* _syncedRecordIDs;
	NSDate* _nextPollDate;
	BOOL _isPolling;
	BOOL _hasPolled;
	BOOL _isPosting;
	NSTimer* _postTimer;
	BOOL _isSubscribed;
	BOOL _dirty;
	PTHTweetbotAccount* _account;
	CKServerChangeToken* _previousServerChangeToken;
	CKRecordZone* _zone;

}

@property (nonatomic,__weak,readonly) PTHTweetbotAccount * account;                      //@synthesize account=_account - In the implementation block
@property (nonatomic,readonly) NSArray * filters; 
@property (nonatomic,__weak,readonly) NSString * filePath; 
@property (assign,getter=isDirty,nonatomic) BOOL dirty;                                  //@synthesize dirty=_dirty - In the implementation block
@property (nonatomic,readonly) BOOL needsPost; 
@property (nonatomic,copy) CKServerChangeToken * previousServerChangeToken;              //@synthesize previousServerChangeToken=_previousServerChangeToken - In the implementation block
@property (nonatomic,retain) CKRecordZone * zone;                                        //@synthesize zone=_zone - In the implementation block
-(BOOL)hasSimilarFilter:(id)arg1 ;
-(void)removeSimilarFilter:(id)arg1 ;
-(void)_post;
-(void)removeFilter:(id)arg1 ;
-(void)migrateOldFilters:(id)arg1 ;
-(BOOL)shouldFilter:(id)arg1 sourceTimelineType:(long long)arg2 ;
-(void)_addFilter:(id)arg1 ;
-(void)_schedulePost;
-(void)_removeFilter:(id)arg1 ;
-(id)filterWithUUID:(id)arg1 ;
-(id)similarFilter:(id)arg1 ;
-(void)_pollIfNeeded;
-(void)_postIfNeeded;
-(void)_didReceiveNotification:(id)arg1 ;
-(void)_poll;
-(void)_importOrMergeCKRecord:(id)arg1 ;
-(id)filterWithRecordID:(id)arg1 ;
-(void)_loadFromUbiquitous;
-(BOOL)needsPost;
-(void)filterDidChange:(id)arg1 ;
-(void)saveIfNeeded;
-(void)loadIfNeeded;
-(void)dealloc;
-(CKRecordZone *)zone;
-(id)description;
-(NSArray *)filters;
-(void)setDirty:(BOOL)arg1 ;
-(NSString *)filePath;
-(void)_subscribe;
-(void)_startSync;
-(CKServerChangeToken *)previousServerChangeToken;
-(void)setPreviousServerChangeToken:(CKServerChangeToken *)arg1 ;
-(void)setZone:(CKRecordZone *)arg1 ;
-(void)addFilter:(id)arg1 ;
-(BOOL)isDirty;
-(id)initWithAccount:(id)arg1 ;
-(PTHTweetbotAccount *)account;
-(void)_sendDidChange;
@end

