/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <SafariServices/SFSafariViewController.h>

@class PTHTweetbotUIActivitySafariViewControllerDelegate, _PTHTweetbotSafariViewControllerTransitioningDelegate, UIView;

@interface PTHTweetbotSafariViewController : SFSafariViewController {

	PTHTweetbotUIActivitySafariViewControllerDelegate* _delegate;
	_PTHTweetbotSafariViewControllerTransitioningDelegate* _transitioningDelegate;
	UIView* _gestureHackView;
	long long _preferredStatusBarStyle;

}

@property (nonatomic,readonly) long long preferredStatusBarStyle;              //@synthesize preferredStatusBarStyle=_preferredStatusBarStyle - In the implementation block
-(id)initWithURL:(id)arg1 entersReaderIfAvailable:(BOOL)arg2 status:(id)arg3 account:(id)arg4 ;
-(void)handleDismiss:(id)arg1 ;
-(id)initWithURL:(id)arg1 entersReaderIfAvailable:(BOOL)arg2 ;
-(long long)preferredStatusBarStyle;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
@end

