/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotWatchMessageObject.h>

@class NSMutableDictionary, PTHTweetbotObjectDescriptor, NSString;

@interface PTHTweetbotWatchObject : NSObject <PTHTweetbotWatchMessageObject> {

	long long _tid;
	long long _accountTID;

}

@property (nonatomic,readonly) NSMutableDictionary * dictionaryRepresentation; 
@property (nonatomic,readonly) long long tid;                                                      //@synthesize tid=_tid - In the implementation block
@property (nonatomic,readonly) long long accountTID;                                               //@synthesize accountTID=_accountTID - In the implementation block
@property (nonatomic,__weak,readonly) PTHTweetbotObjectDescriptor * objectDescriptor; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)cacheTweetbotObject:(id)arg1 ;
+(BOOL)supportsSecureCoding;
-(long long)accountTID;
-(PTHTweetbotObjectDescriptor *)objectDescriptor;
-(id)initWithTID:(long long)arg1 accountTID:(long long)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSMutableDictionary *)dictionaryRepresentation;
-(id)initWithDictionaryRepresentation:(id)arg1 ;
-(long long)tid;
@end

