/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@class UIView, _PTHTweetbotNoticeView, UIDynamicAnimator, NSTimer, PTHTweetbotNotice;

@interface PTHTweetbotNoticeController : NSObject {

	UIView* _containerView;
	_PTHTweetbotNoticeView* _noticeView;
	UIDynamicAnimator* _animator;
	BOOL _needsToPlaySound;
	NSTimer* _hideTimer;
	/*^block*/id _didHide;
	PTHTweetbotNotice* _notice;

}

@property (nonatomic,readonly) PTHTweetbotNotice * notice;              //@synthesize notice=_notice - In the implementation block
+(void)showSuccessNotice:(id)arg1 message:(id)arg2 ;
+(void)showNotice:(id)arg1 ;
+(void)playSuccessSound;
+(void)beginQueuingNotifications;
+(void)endQueuingNotifications;
+(void)showFailureNotice:(id)arg1 message:(id)arg2 ;
+(void)_processQueue;
-(id)initWithNotice:(id)arg1 ;
-(void)showInController:(id)arg1 didHide:(/*^block*/id)arg2 ;
-(void)_hideTimeout;
-(void)_disableAnimator;
-(void)_setupHideTimer;
-(void)_didHide:(long long)arg1 ;
-(void)_setupAnimator:(BOOL)arg1 ;
-(void)_pan:(id)arg1 ;
-(void)_hide:(long long)arg1 ;
-(id)init;
-(id)description;
-(PTHTweetbotNotice *)notice;
@end

