/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <PTHCommon/PTHViewController.h>
#import <UIKit/UITextFieldDelegate.h>

@class PTHTweetbotAccount, PTHStaticSectionCell, NSString;

@interface PTHTweetbotServiceLoginSettingsController : PTHViewController <UITextFieldDelegate> {

	PTHTweetbotAccount* _account;
	Class _serviceClass;
	PTHStaticSectionCell* _usernameCell;
	PTHStaticSectionCell* _passwordCell;
	BOOL _isLoggedIn;

}

@property (nonatomic,readonly) BOOL isLoggedIn;                     //@synthesize isLoggedIn=_isLoggedIn - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithAccount:(id)arg1 serviceClass:(Class)arg2 ;
-(BOOL)isLoggedIn;
-(void)loadView;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)updateUI;
-(void)login;
@end

