/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotStatusCursorController.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@class PTHTweetbotAccount, UILongPressGestureRecognizer, PTHTweetbotHomeTimelineListPickerController, PTHTweetbotList, NSString;

@interface PTHTweetbotHomeTimelineController : PTHTweetbotStatusCursorController <UIGestureRecognizerDelegate> {

	PTHTweetbotAccount* _account;
	UILongPressGestureRecognizer* _listPickerRecognizer;
	PTHTweetbotHomeTimelineListPickerController* _listPicker;
	PTHTweetbotList* _list;

}

@property (nonatomic,retain) PTHTweetbotList * list;                //@synthesize list=_list - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)searchTitle;
-(id)nothingFoundTitle;
-(void)_updateUnreadTab;
-(void)showListPicker;
-(void)_pickList:(id)arg1 ;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(void)didMoveToParentViewController:(id)arg1 ;
-(void)willMoveToParentViewController:(id)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)setList:(PTHTweetbotList *)arg1 ;
-(PTHTweetbotList *)list;
-(id)initWithAccount:(id)arg1 ;
@end

