/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotAvatarDetailCell.h>

@class PTHShapeView, PTHTweetbotDirectMessageThread;

@interface PTHTweetbotDirectMessageThreadCell : PTHTweetbotAvatarDetailCell {

	PTHShapeView* _readIndicator;

}

@property (nonatomic,readonly) PTHTweetbotDirectMessageThread * thread; 
+(void)initialize;
+(double)textHeight;
-(void)_updateDirectMessageThread;
-(void)colorThemeDidChange;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(void)setItem:(id)arg1 ;
-(PTHTweetbotDirectMessageThread *)thread;
@end

