/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <PTHCommon/PTHViewController.h>

@class PTHTweetbotAccount, NSArray, UIScrollView, PTHStaticSectionView, PTHStaticSectionCell, NSString;

@interface PTHTweetbotServicesSettingsController : PTHViewController {

	PTHTweetbotAccount* _account;
	NSArray* _serviceClasses;
	UIScrollView* _scrollView;
	PTHStaticSectionView* _section;
	PTHStaticSectionCell* _showMarkerCell;
	NSString* _currentServiceKey;
	NSString* _descriptionTitle;
	PTHStaticSectionCell* _selectedCell;

}

@property (nonatomic,retain) NSString * currentServiceKey;                     //@synthesize currentServiceKey=_currentServiceKey - In the implementation block
@property (nonatomic,copy) NSString * descriptionTitle;                        //@synthesize descriptionTitle=_descriptionTitle - In the implementation block
@property (nonatomic,retain) PTHStaticSectionCell * selectedCell;              //@synthesize selectedCell=_selectedCell - In the implementation block
@property (assign,nonatomic,__weak) Class currentServiceClass; 
-(void)setDescriptionTitle:(NSString *)arg1 ;
-(id)initWithAccount:(id)arg1 serviceClasses:(id)arg2 ;
-(void)setCurrentServiceKey:(NSString *)arg1 ;
-(Class)currentServiceClass;
-(void)setCurrentServiceClass:(Class)arg1 ;
-(NSString *)currentServiceKey;
-(NSString *)descriptionTitle;
-(void)_selectedCell:(id)arg1 ;
-(PTHStaticSectionCell *)selectedCell;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)setSelectedCell:(PTHStaticSectionCell *)arg1 ;
@end

