/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@interface PTHTweetbotMediaParser : NSObject
+(void)loadURLForMedium:(id)arg1 response:(/*^block*/id)arg2 ;
+(void)loadPreviewURLDictionaryForMedium:(id)arg1 response:(/*^block*/id)arg2 ;
+(id)parserClasses;
+(id)parsableHosts;
+(id)normalizedHostForURL:(id)arg1 ;
+(double)previewAspectRatioForMedium:(id)arg1 ;
+(id)createMediumFromEntity:(id)arg1 ;
+(long long)mediumTypeForURL:(id)arg1 ;
+(void)loadMediumTypeFromURLMimeType:(id)arg1 response:(/*^block*/id)arg2 ;
+(void)loadMediumFromCard:(id)arg1 response:(/*^block*/id)arg2 ;
+(void)initialize;
@end

