/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <PTHCommon/PTHColorGroupTableViewCell.h>

@class UIView;

@interface PTHTweetbotMessageCell : PTHColorGroupTableViewCell {

	UIView* _bottomSeparatorView;
	UIView* _topSeparatorView;

}

@property (assign,getter=hasTopSeparator,nonatomic) BOOL topSeparator; 
@property (assign,getter=hasBottomSeparator,nonatomic) BOOL bottomSeparator; 
+(id)cellWithText:(id)arg1 ;
+(id)reuseIdentifier;
-(BOOL)hasTopSeparator;
-(BOOL)hasBottomSeparator;
-(id)init;
-(id)initWithText:(id)arg1 ;
-(void)setTopSeparator:(BOOL)arg1 ;
-(void)setBottomSeparator:(BOOL)arg1 ;
@end

