/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <PTHCommon/PTHViewController.h>

@class PTHTweetbotAccount;

@interface PTHTweetbotAccountSettingsController : PTHViewController {

	PTHTweetbotAccount* _account;

}
-(void)_showDeveloperSettings:(id)arg1 ;
-(void)_showPushSettings:(id)arg1 ;
-(void)_showURLShortnerServices:(id)arg1 ;
-(void)_showImageUploadServices:(id)arg1 ;
-(void)_showMovieUploadServices:(id)arg1 ;
-(void)_showBookmarkers:(id)arg1 ;
-(void)_resetCache:(id)arg1 ;
-(void)loadView;
-(id)initWithAccount:(id)arg1 ;
@end

