/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@class NSString;

@interface PTHTweetbotBrowserLauncher : NSObject {

	NSString* _name;
	NSString* _scheme;
	NSString* _launchURLString;

}

@property (nonatomic,copy) NSString * name;                         //@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString * scheme;                       //@synthesize scheme=_scheme - In the implementation block
@property (nonatomic,copy) NSString * launchURLString;              //@synthesize launchURLString=_launchURLString - In the implementation block
+(id)availableBrowserLaunchers;
+(id)defaultBrowserName;
+(id)defaultBrowserLauncher;
+(id)browserLauncherWithScheme:(id)arg1 ;
+(void)openURL:(id)arg1 ;
-(void)setLaunchURLString:(NSString *)arg1 ;
-(NSString *)launchURLString;
-(BOOL)isEqual:(id)arg1 ;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(NSString *)scheme;
-(void)openURL:(id)arg1 ;
-(void)setScheme:(NSString *)arg1 ;
@end

