/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <PTHCommon/PTHViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>

@class PTHTweetbotAccount, UITableView, UILabel, NSMutableArray, _PTHTweetbotMuteAddButton, NSString;

@interface PTHTweetbotMuteController : PTHViewController <UITableViewDelegate, UITableViewDataSource> {

	PTHTweetbotAccount* _account;
	UITableView* _tableView;
	UILabel* _footerLabel;
	NSMutableArray* _userFilters;
	_PTHTweetbotMuteAddButton* _userAddButton;
	NSMutableArray* _keywordFilters;
	_PTHTweetbotMuteAddButton* _keywordAddButton;
	NSMutableArray* _hashtagFilters;
	_PTHTweetbotMuteAddButton* _hashtagAddButton;
	NSMutableArray* _sourceFilters;
	_PTHTweetbotMuteAddButton* _sourceAddButton;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)initialize;
-(void)toggleMode;
-(id)_filterAtIndexPath:(id)arg1 ;
-(void)_updateFilters:(BOOL)arg1 ;
-(id)_itemAtIndexPath:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)reloadData;
-(void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3 ;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2 ;
-(BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2 ;
-(BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLayoutSubviews;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)_updateFilters;
-(void)_add:(id)arg1 ;
-(id)initWithAccount:(id)arg1 ;
@end

