/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@class PTHTweetbotAccountData;

@interface PTHTweetbotAccountDataMonitor : NSObject {

	unsigned long long _minuteHeartbeatCounter;
	unsigned long long _monitorCount;
	BOOL _isMonitoring;
	BOOL _loaded;
	BOOL _streaming;
	PTHTweetbotAccountData* _accountData;

}

@property (nonatomic,__weak,readonly) PTHTweetbotAccountData * accountData;              //@synthesize accountData=_accountData - In the implementation block
@property (nonatomic,readonly) BOOL isMonitoring;                                        //@synthesize isMonitoring=_isMonitoring - In the implementation block
@property (assign,getter=isLoaded,nonatomic) BOOL loaded;                                //@synthesize loaded=_loaded - In the implementation block
@property (assign,getter=isStreaming,nonatomic) BOOL streaming;                          //@synthesize streaming=_streaming - In the implementation block
-(PTHTweetbotAccountData *)accountData;
-(void)pushMonitor;
-(void)popMonitor;
-(void)_minuteHeartbeat;
-(id)initWithAccountData:(id)arg1 ;
-(void)update:(BOOL)arg1 streamed:(BOOL)arg2 ;
-(void)_streamingStopped;
-(void)_interactionsDidChange:(id)arg1 ;
-(void)startMonitoring;
-(BOOL)isMonitoring;
-(void)setLoaded:(BOOL)arg1 ;
-(void)dealloc;
-(id)init;
-(BOOL)isLoaded;
-(BOOL)isStreaming;
-(void)stopMonitoring;
-(void)setStreaming:(BOOL)arg1 ;
@end

