/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <UIKit/UIActivityViewController.h>

@class UIVisualEffectView, UILabel, NSString;

@interface PTHTweetbotActivityViewController : UIActivityViewController {

	UIVisualEffectView* _sourceTitleView;
	UILabel* _sourceTitleLabel;
	NSString* _sourceTitle;

}

@property (nonatomic,retain) NSString * sourceTitle;              //@synthesize sourceTitle=_sourceTitle - In the implementation block
-(void)setSourceTitle:(NSString *)arg1 ;
-(BOOL)_isInPopover;
-(NSString *)sourceTitle;
-(id)_sourceTitleContainerView;
-(void)viewDidLayoutSubviews;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)_layoutTitleView;
@end

