/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotCursor.h>

@interface PTHTweetbotCurrentUserMentionsCursor : PTHTweetbotCursor
+(unsigned long long)itemSaveCount;
+(Class)itemClass;
-(BOOL)canSync;
-(void)_removeUser:(id)arg1 ;
-(BOOL)canAddItem:(id)arg1 ;
-(void)_loadQuotesSinceTID:(long long)arg1 maxTID:(long long)arg2 newMentions:(id)arg3 block:(/*^block*/id)arg4 ;
-(void)reallyLoadNewer:(/*^block*/id)arg1 ;
-(void)reallyLoadOlder:(/*^block*/id)arg1 ;
-(void)reallyLoadGap:(/*^block*/id)arg1 ;
-(void)_applyFilters:(id)arg1 ;
-(BOOL)hasReadStatus;
-(BOOL)usesTIDPagination;
-(id)requestURLString;
-(id)queryDictionary;
-(void)dealloc;
-(BOOL)isPersistent;
-(id)uniqueID;
-(void)setAccount:(id)arg1 ;
@end

