/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@class NSMapTable, NSTimer, NSDate;

@interface PTHTweetbotHeartbeatController : NSObject {

	NSMapTable* _secondNotificationsMapTable;
	NSTimer* _secondTimer;
	NSMapTable* _minuteNotificationsMapTable;
	NSTimer* _minuteTimer;
	NSDate* _lastMinuteHeartbeatSent;

}
+(id)sharedController;
-(void)addMinuteObserver:(id)arg1 selector:(SEL)arg2 ;
-(void)removeSecondObserver:(id)arg1 ;
-(void)addSecondObserver:(id)arg1 selector:(SEL)arg2 ;
-(void)removeMinuteObserver:(id)arg1 ;
-(void)_didStart;
-(void)_willStop;
-(void)_startupSecondTimer;
-(void)_sendSecondHeartbeat;
-(void)_startupMinuteTimer;
-(void)_sendMinuteHeartbeat;
-(void)_shutdownMinuteTimer;
-(void)_shutdownSecondTimer;
-(void)dealloc;
-(id)init;
@end

