/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@protocol NSSecureCoding, PTHTweetbotWatchMessageObject;
@class NSError, NSObject, NSDictionary;

@interface PTHTweetbotWatchReply : NSObject <NSSecureCoding> {

	BOOL _isError;
	NSError* _error;
	NSObject*<NSSecureCoding> _object;
	id _propertyList;
	id<PTHTweetbotWatchMessageObject> _messageObject;

}

@property (nonatomic,readonly) NSObject*<NSSecureCoding> object;                           //@synthesize object=_object - In the implementation block
@property (nonatomic,readonly) id propertyList;                                            //@synthesize propertyList=_propertyList - In the implementation block
@property (nonatomic,retain) id<PTHTweetbotWatchMessageObject> messageObject;              //@synthesize messageObject=_messageObject - In the implementation block
@property (assign,nonatomic) BOOL isError;                                                 //@synthesize isError=_isError - In the implementation block
@property (nonatomic,readonly) NSError * error;                                            //@synthesize error=_error - In the implementation block
@property (nonatomic,readonly) NSDictionary * dictionaryRepresentation; 
+(id)dictionaryWithTweetbotError:(id)arg1 ;
+(id)dataWithTweetbotError:(id)arg1 ;
+(BOOL)supportsSecureCoding;
-(id)initWithTweetbotError:(id)arg1 ;
-(id<PTHTweetbotWatchMessageObject>)messageObject;
-(id)initWithMessageObject:(id)arg1 ;
-(void)setMessageObject:(id<PTHTweetbotWatchMessageObject>)arg1 ;
-(void)setIsError:(BOOL)arg1 ;
-(id)propertyList;
-(NSError *)error;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)description;
-(NSObject*<NSSecureCoding>)object;
-(NSDictionary *)dictionaryRepresentation;
-(id)initWithObject:(id)arg1 ;
-(id)initWithDictionaryRepresentation:(id)arg1 ;
-(BOOL)isError;
-(id)initWithError:(id)arg1 ;
-(id)initWithPropertyList:(id)arg1 ;
@end

