/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotAccountDataLoader.h>

@class NSDate, NSMutableArray;

@interface PTHTweetbotAccountDataUserLoader : PTHTweetbotAccountDataLoader {

	NSDate* _lastLoadedDate;
	unsigned long long _searchCounter;
	NSMutableArray* _updateUsers;

}
-(BOOL)canUpdate;
-(void)dispatchFindUsers:(id)arg1 options:(unsigned long long)arg2 limit:(unsigned long long)arg3 block:(/*^block*/id)arg4 ;
-(id)initWithAccountData:(id)arg1 ;
-(id)setup:(id)arg1 userVersion:(long long)arg2 ;
-(id)verify:(id)arg1 ;
-(void)_updateUser:(id)arg1 ;
-(id)userWithTIDValue:(id)arg1 connection:(id)arg2 ;
-(void)updateIfNeeded;
-(void)dealloc;
-(void)update;
-(id)tableName;
@end

