/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <UIKit/UIView.h>

@class UIView, PTHProgressView, PTHShapeView, UILabel, NSString;

@interface PTHTweetbotViewControllerStateView : UIView {

	UIView* _contentView;
	PTHProgressView* _progressView;
	PTHShapeView* _circleView;
	UILabel* _messageLabel;
	CGRect _keyboardFrame;
	BOOL _keyboardVisible;
	long long _state;

}

@property (assign,nonatomic) long long state;                         //@synthesize state=_state - In the implementation block
@property (nonatomic,copy) NSString * nothingFoundTitle; 
+(void)showViewControllerContentAnimations:(/*^block*/id)arg1 completion:(/*^block*/id)arg2 ;
-(NSString *)nothingFoundTitle;
-(void)setNothingFoundTitle:(NSString *)arg1 ;
-(void)_keyboardWillChange:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(long long)state;
-(void)setState:(long long)arg1 ;
-(void)setState:(long long)arg1 animated:(BOOL)arg2 ;
@end

