/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <Tweetbot/PTHTweetbotSyncCloudController.h>

@class NSMutableDictionary;

@interface PTHTweetbotSyncCloudPositionController : PTHTweetbotSyncCloudController {

	NSMutableDictionary* _dirtyRecords;

}
+(id)sharedController;
-(void)post:(/*^block*/id)arg1 ;
-(void)markCursorSynced:(id)arg1 ;
-(long long)lastReadTIDForCursor:(id)arg1 ;
-(SCD_Struct_PT3)pendingSyncPositionForCursor:(id)arg1 ;
-(void)willStart;
-(void)didShutdown;
-(void)poll:(/*^block*/id)arg1 ;
-(void)receivedQueryNotification:(id)arg1 ;
-(void)_cursorWasScrolled:(id)arg1 ;
-(id)syncIdentifierForCursorUniqueID:(id)arg1 ;
-(void)setSyncIdentifier:(id)arg1 forCursorUniqueID:(id)arg2 ;
-(SCD_Struct_PT3)pendingSyncPositionForCursorUniqueID:(id)arg1 ;
-(long long)lastReadTIDForCursorUniqueID:(id)arg1 ;
-(void)setPendingSyncPosition:(SCD_Struct_PT3)arg1 forCursorUniqueID:(id)arg2 ;
-(void)setLastReadTID:(long long)arg1 forCursorUniqueID:(id)arg2 ;
-(void)_processRecordName:(id)arg1 recordFields:(id)arg2 ;
-(id)notificationInfo;
-(id)recordType;
@end

