/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/WCSessionDelegate.h>

@class NSString;

@interface PTHTweetbotWatchController : NSObject <WCSessionDelegate> {

	BOOL _isWatchAppInstalled;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedController;
-(void)_accountsDidUpdate;
-(id)init;
-(void)session:(id)arg1 didReceiveMessage:(id)arg2 replyHandler:(/*^block*/id)arg3 ;
-(void)session:(id)arg1 didReceiveMessageData:(id)arg2 replyHandler:(/*^block*/id)arg3 ;
-(void)session:(id)arg1 didReceiveApplicationContext:(id)arg2 ;
-(void)sessionWatchStateDidChange:(id)arg1 ;
@end

