/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotCell.h>

@class UIView, UIImageView, UILabel, PTHProgressView;

@interface PTHTweetbotCursorGapCell : PTHTweetbotCell {

	UIView* _loadingContainerView;
	UIImageView* _arrowView;
	UILabel* _loadLabel;
	PTHProgressView* _progressView;
	BOOL _isShowingProgress;
	unsigned long long _loadRectEdge;

}

@property (assign,nonatomic) unsigned long long loadRectEdge;              //@synthesize loadRectEdge=_loadRectEdge - In the implementation block
-(void)setLoadRectEdge:(unsigned long long)arg1 animated:(BOOL)arg2 ;
-(void)setLoadRectEdge:(unsigned long long)arg1 ;
-(void)setShowProgress:(BOOL)arg1 animated:(BOOL)arg2 ;
-(unsigned long long)loadRectEdge;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
@end

