/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <Tweetbot/PTHTweetbotUser.h>

@class PTHTweetbotCursor, PTHTweetbotListsCursor;

@interface PTHTweetbotCurrentUser : PTHTweetbotUser {

	PTHTweetbotCursor* _homeTimelineCursor;
	PTHTweetbotCursor* _mentionsCursor;
	PTHTweetbotListsCursor* _listsCursor;
	PTHTweetbotCursor* _favoritesCursor;
	PTHTweetbotCursor* _retweetsOfMeCursor;
	PTHTweetbotCursor* _savedSearchesCursor;

}

@property (nonatomic,readonly) PTHTweetbotCursor * homeTimelineCursor; 
@property (nonatomic,readonly) PTHTweetbotCursor * savedSearchesCursor; 
@property (nonatomic,readonly) PTHTweetbotCursor * retweetsOfMeCursor; 
@property (nonatomic,readonly) PTHTweetbotCursor * mentionsCursor; 
@property (nonatomic,readonly) PTHTweetbotCursor * favoritesCursor; 
@property (nonatomic,readonly) PTHTweetbotListsCursor * listsCursor; 
+(void)createMimeDataForImage:(id)arg1 imageUTI:(id)arg2 maxImageSize:(CGSize)arg3 maxFileSize:(unsigned long long)arg4 result:(/*^block*/id)arg5 ;
-(id)initWithAccount:(id)arg1 tid:(long long)arg2 ;
-(PTHTweetbotCursor *)mentionsCursor;
-(PTHTweetbotCursor *)favoritesCursor;
-(PTHTweetbotCursor *)savedSearchesCursor;
-(PTHTweetbotListsCursor *)listsCursor;
-(PTHTweetbotCursor *)homeTimelineCursor;
-(void)updateProfileWithName:(id)arg1 urlString:(id)arg2 location:(id)arg3 description:(id)arg4 result:(/*^block*/id)arg5 ;
-(void)updateProfileImage:(id)arg1 imageUTI:(id)arg2 result:(/*^block*/id)arg3 ;
-(void)updateBannerImage:(id)arg1 imageUTI:(id)arg2 result:(/*^block*/id)arg3 ;
-(PTHTweetbotCursor *)retweetsOfMeCursor;
-(BOOL)isCurrentUser;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(void)reset;
-(void)setScreenName:(id)arg1 ;
-(void)setAccount:(id)arg1 ;
@end

