/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotLoadingTableViewController.h>

@class PTHTweetbotUser, PTHTweetbotListsCursor, NSMutableArray, UIBarButtonItem;

@interface PTHTweetbotManageListMembershipsController : PTHTweetbotLoadingTableViewController {

	PTHTweetbotUser* _user;
	PTHTweetbotListsCursor* _listsCursor;
	NSMutableArray* _addedLists;
	NSMutableArray* _changedLists;
	BOOL _loadedMemberships;
	UIBarButtonItem* _saveBarButtonItem;

}
+(Class)cellClass;
-(id)initWithTweetbotUser:(id)arg1 ;
-(void)configure:(id)arg1 forItem:(id)arg2 ;
-(void)loadDataIfNeeded:(BOOL)arg1 ;
-(void)save;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
@end

