/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <PTHCommon/PTHViewController.h>

@class PTHTweetbotAccount, UISegmentedControl, PTHTweetbotStatisticsController, PTHTweetbotActivityController, UIViewController;

@interface PTHTweetbotAccountDataController : PTHViewController {

	PTHTweetbotAccount* _account;
	UISegmentedControl* _modeSegmentedControl;
	PTHTweetbotStatisticsController* _statiticsController;
	PTHTweetbotActivityController* _activityController;
	UIViewController* _childController;
	unsigned long long _mode;

}
-(BOOL)shouldShowPushNotification:(id)arg1 ;
-(void)_changeMode:(id)arg1 ;
-(id)controllerForMode:(unsigned long long)arg1 ;
-(void)showStats;
-(id)initWithCoder:(id)arg1 ;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)scrollToTop;
-(void)showActivity;
-(id)initWithAccount:(id)arg1 ;
@end

