/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotSetupChildController.h>

@class NSArray, ACAccountStore;

@interface PTHTweetbotSetupChooseController : PTHTweetbotSetupChildController {

	NSArray* _acAccounts;
	ACAccountStore* _store;
	BOOL _signIn;

}
-(id)initWithACAccounts:(id)arg1 store:(id)arg2 ;
-(id)pickerTitles;
-(void)_action:(id)arg1 ;
-(void)_signIn:(id)arg1 ;
-(void)_choose:(id)arg1 ;
-(id)colorGroupName;
-(void)loadView;
-(void)_selectionChanged;
@end

