/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <PTHCommon/PTHViewController.h>
#import <UIKit/UIViewControllerAnimatedTransitioning.h>

@class PTHTweetbotAccount, UIViewController, UILongPressGestureRecognizer, UIVisualEffectView, UIScrollView, NSMutableArray, NSLayoutConstraint, PTHTweetbotList, NSString;

@interface PTHTweetbotHomeTimelineListPickerController : PTHViewController <UIViewControllerAnimatedTransitioning> {

	PTHTweetbotAccount* _account;
	UIViewController* _sourceController;
	UILongPressGestureRecognizer* _listPickerRecognizer;
	UIVisualEffectView* _effectView;
	UIScrollView* _scrollView;
	NSMutableArray* _listViews;
	NSLayoutConstraint* _showConstraint;
	NSLayoutConstraint* _hideConstraint;
	PTHTweetbotList* _selectedList;

}

@property (nonatomic,retain) PTHTweetbotList * selectedList;              //@synthesize selectedList=_selectedList - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)gestureRecognizerChanged:(id)arg1 ;
-(void)setSelectedList:(PTHTweetbotList *)arg1 ;
-(PTHTweetbotList *)selectedList;
-(void)_selectedList:(id)arg1 ;
-(void)presentTransition:(id)arg1 ;
-(void)dismissTransition:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(double)transitionDuration:(id)arg1 ;
-(void)animateTransition:(id)arg1 ;
-(long long)preferredStatusBarStyle;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)_dismiss;
-(id)initWithAccount:(id)arg1 ;
@end

