/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <UIKit/UIView.h>

@protocol UILayoutSupport;
@class UIView, NSLayoutConstraint, UINavigationBar;

@interface PTHTweetbotAccountNavigationBarFiller : UIView {

	UIView* _statusBarFiller;
	id<UILayoutSupport> _topLayoutGuide;
	NSLayoutConstraint* _topLayoutGuideConstraint;
	UINavigationBar* _navigationBar;

}

@property (nonatomic,readonly) UINavigationBar * navigationBar;               //@synthesize navigationBar=_navigationBar - In the implementation block
@property (nonatomic,retain) id<UILayoutSupport> topLayoutGuide;              //@synthesize topLayoutGuide=_topLayoutGuide - In the implementation block
+(BOOL)requiresConstraintBasedLayout;
-(void)colorThemeDidChange;
-(id)initWithFrame:(CGRect)arg1 ;
-(UINavigationBar *)navigationBar;
-(id<UILayoutSupport>)topLayoutGuide;
-(void)setTopLayoutGuide:(id<UILayoutSupport>)arg1 ;
@end

