/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotDirectMessage.h>

@class PTHTweetbotPostDraft;

@interface PTHTweetbotDirectMessageDraft : PTHTweetbotDirectMessage {

	BOOL _postingFailed;
	PTHTweetbotPostDraft* _draft;

}

@property (nonatomic,readonly) PTHTweetbotPostDraft * draft;              //@synthesize draft=_draft - In the implementation block
-(PTHTweetbotPostDraft *)draft;
-(void)destroy:(/*^block*/id)arg1 ;
-(void)post:(/*^block*/id)arg1 ;
-(BOOL)isSentMessage;
-(BOOL)postingFailed;
-(id)initWithAccount:(id)arg1 tid:(long long)arg2 draft:(id)arg3 ;
-(long long)otherUserTID;
-(long long)recipientUserTID;
-(long long)senderUserTID;
-(BOOL)isReceivedMessage;
-(void)store;
-(id)text;
-(id)attributedText;
-(void)remove;
-(BOOL)isDraft;
-(id)entities;
@end

