/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotStatusDetailChildController.h>

@class PTHTweetbotStatusView;

@interface PTHTweetbotStatusDetailStatusController : PTHTweetbotStatusDetailChildController {

	PTHTweetbotStatusView* _statusView;
	unsigned long long _topSeparatorStyle;

}

@property (assign,nonatomic) unsigned long long topSeparatorStyle;              //@synthesize topSeparatorStyle=_topSeparatorStyle - In the implementation block
-(void)setTopSeparatorStyle:(unsigned long long)arg1 ;
-(void)statusWasUpdated;
-(unsigned long long)topSeparatorStyle;
-(void)loadView;
-(id)initWithStatus:(id)arg1 ;
@end

