/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotStatusDetailChildController.h>

@class PTHButton, UIView;

@interface PTHTweetbotStatusDetailActionController : PTHTweetbotStatusDetailChildController {

	PTHButton* _favoritesButton;
	PTHButton* _dateButton;
	PTHButton* _retweetsButton;
	PTHButton* _viaButton;
	unsigned long long _favoriteCount;
	unsigned long long _retweetCount;
	UIView* _dateBottomLineView;
	UIView* _viaBottomLineView;

}
-(void)_updateDate;
-(void)statusWasUpdated;
-(void)_showFavorites:(id)arg1 ;
-(void)_showRetweets:(id)arg1 ;
-(void)_showWebPage:(id)arg1 ;
-(void)_showClient:(id)arg1 ;
-(void)_showClientOptions:(id)arg1 ;
-(void)activityWasUpdated;
-(void)_updateFavoritesCount;
-(void)_updateRetweetsCount;
-(void)_updateVia;
-(void)_updateButton:(id)arg1 withMarkdownTitle:(id)arg2 ;
-(void)previewingStatusDidChange;
-(void)loadView;
-(void)_updateButtons;
@end

