/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <UIKit/UIView.h>

@class PTHProgressView, UILabel, NSDateFormatter, NSDate;

@interface PTHTweetbotRefreshView : UIView {

	PTHProgressView* _progressView;
	UILabel* _refreshTitleLabel;
	UILabel* _updateDateLabel;
	NSDateFormatter* _updateDateFormatter;
	BOOL _refreshing;
	BOOL _streaming;
	double _progress;
	NSDate* _updateDate;

}

@property (assign,nonatomic) double progress;                                    //@synthesize progress=_progress - In the implementation block
@property (nonatomic,retain) NSDate * updateDate;                                //@synthesize updateDate=_updateDate - In the implementation block
@property (getter=isRefreshing,nonatomic,readonly) BOOL refreshing;              //@synthesize refreshing=_refreshing - In the implementation block
@property (getter=isStreaming,nonatomic,readonly) BOOL streaming;                //@synthesize streaming=_streaming - In the implementation block
-(void)_updateDate;
-(void)startStreaming;
-(void)startRefresh;
-(void)stopRefresh;
-(void)didMoveToWindow:(id)arg1 ;
-(void)_updateProgress;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(CGSize)intrinsicContentSize;
-(void)setProgress:(double)arg1 ;
-(double)progress;
-(BOOL)isRefreshing;
-(BOOL)isStreaming;
-(void)stopStreaming;
-(NSDate *)updateDate;
-(void)setUpdateDate:(NSDate *)arg1 ;
@end

