/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <UIKit/UIView.h>

@class PTHTweetbotStatisticsHeaderGraphView, UIView, UILabel, NSMutableArray, NSDictionary;

@interface PTHTweetbotStatisticsHeaderView : UIView {

	PTHTweetbotStatisticsHeaderGraphView* _graphView;
	UIView* _countsView;
	UIView* _countsTopLine;
	UIView* _countsBottomLine;
	UILabel* _mainCountLabel;
	UILabel* _mainCountTitleLabel;
	UILabel* _favoritesCountLabel;
	UILabel* _retweetsCountLabel;
	UILabel* _followersCountLabel;
	NSMutableArray* _layoutConstraints;
	NSDictionary* _recentDailyInteractionCounts;
	UIView* _activityTipPointerView;

}

@property (nonatomic,retain) NSDictionary * recentDailyInteractionCounts;              //@synthesize recentDailyInteractionCounts=_recentDailyInteractionCounts - In the implementation block
@property (nonatomic,readonly) UIView * activityTipPointerView;                        //@synthesize activityTipPointerView=_activityTipPointerView - In the implementation block
-(void)setRecentDailyInteractionCounts:(NSDictionary *)arg1 ;
-(NSDictionary *)recentDailyInteractionCounts;
-(UIView *)activityTipPointerView;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
@end

