/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <PTHCommon/PTHButton.h>

@class PTHShapeView, UIViewController, UITabBarItem, PTHTweetbotAccountTabBar;

@interface PTHTweetbotAccountTabBarItemView : PTHButton {

	PTHShapeView* _unreadView;
	BOOL _unread;
	UIViewController* _viewController;
	UITabBarItem* _item;
	PTHTweetbotAccountTabBar* _tabBar;

}

@property (assign,nonatomic,__weak) UIViewController * viewController;              //@synthesize viewController=_viewController - In the implementation block
@property (nonatomic,readonly) UITabBarItem * item;                                 //@synthesize item=_item - In the implementation block
@property (assign,nonatomic,__weak) PTHTweetbotAccountTabBar * tabBar;              //@synthesize tabBar=_tabBar - In the implementation block
@property (assign,getter=hasUnread,nonatomic) BOOL unread;                          //@synthesize unread=_unread - In the implementation block
-(void)_tapped;
-(void)hideUnread:(BOOL)arg1 ;
-(void)showUnread:(BOOL)arg1 ;
-(id)colorGroupName;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(UITabBarItem *)item;
-(void)setViewController:(UIViewController *)arg1 ;
-(UIViewController *)viewController;
-(PTHTweetbotAccountTabBar *)tabBar;
-(void)setTabBar:(PTHTweetbotAccountTabBar *)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)setUnread:(BOOL)arg1 ;
-(BOOL)hasUnread;
@end

