/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <UIKit/UIControl.h>
#import <UIKit/UITextViewDelegate.h>

@class PTHTextView, NSLayoutConstraint, PTHButton, UILabel, PTHTweetbotPostDraft, NSString;

@interface PTHTweetbotDirectMessageTextView : UIControl <UITextViewDelegate> {

	PTHTextView* _textView;
	NSLayoutConstraint* _textViewHeightConstraint;
	long long _directMessageMaxLength;
	PTHButton* _sendButton;
	UILabel* _counterLabel;
	PTHTweetbotPostDraft* _draft;

}

@property (nonatomic,copy) NSString * text; 
@property (nonatomic,retain) PTHTweetbotPostDraft * draft;              //@synthesize draft=_draft - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(PTHTweetbotPostDraft *)draft;
-(void)setDraft:(PTHTweetbotPostDraft *)arg1 ;
-(void)_send;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(BOOL)becomeFirstResponder;
-(id)keyCommands;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(void)textViewDidChange:(id)arg1 ;
@end

