/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@class NSDate, NSTimer, NSString, CKNotificationInfo, CKDatabase;

@interface PTHTweetbotSyncCloudController : NSObject {

	BOOL _isSubscribed;
	NSDate* _nextPollDate;
	BOOL _isPolling;
	BOOL _hasPolled;
	BOOL _isPosting;
	NSTimer* _postingTimer;
	double _postingTimerInterval;
	BOOL _pollAfterPost;
	BOOL _dirty;
	NSDate* _latestModificationDate;
	NSString* _subscriptionID;
	NSString* _recordType;
	CKNotificationInfo* _notificationInfo;

}

@property (nonatomic,readonly) CKDatabase * database; 
@property (nonatomic,readonly) NSString * subscriptionID;                           //@synthesize subscriptionID=_subscriptionID - In the implementation block
@property (assign,getter=isDirty,nonatomic) BOOL dirty;                             //@synthesize dirty=_dirty - In the implementation block
@property (nonatomic,retain) NSDate * latestModificationDate;                       //@synthesize latestModificationDate=_latestModificationDate - In the implementation block
@property (nonatomic,readonly) BOOL isModificationDatePersistent; 
@property (nonatomic,readonly) NSString * recordType;                               //@synthesize recordType=_recordType - In the implementation block
@property (nonatomic,readonly) CKNotificationInfo * notificationInfo;               //@synthesize notificationInfo=_notificationInfo - In the implementation block
@property (nonatomic,readonly) unsigned long long subscriptionOptions; 
@property (nonatomic,readonly) double slowPollTimeInterval; 
@property (nonatomic,readonly) double fastPollTimeInterval; 
@property (nonatomic,readonly) double minimumPostTimeInterval; 
@property (nonatomic,readonly) double maximunPostTimeInterval; 
+(BOOL)isRegisteredForPush;
+(id)database;
-(void)post:(/*^block*/id)arg1 ;
-(void)_didEnterBackground;
-(void)_reachabilityDidChange;
-(void)_pollIfNeeded;
-(void)_postIfNeeded;
-(void)_didReceiveNotification:(id)arg1 ;
-(void)willStart;
-(double)minimumPostTimeInterval;
-(void)_schedulePostTimer;
-(BOOL)isModificationDatePersistent;
-(NSDate *)latestModificationDate;
-(void)setLatestModificationDate:(NSDate *)arg1 ;
-(void)_shutdownSync;
-(void)didShutdown;
-(void)poll:(/*^block*/id)arg1 ;
-(double)maximunPostTimeInterval;
-(void)receivedQueryNotification:(id)arg1 ;
-(double)slowPollTimeInterval;
-(double)fastPollTimeInterval;
-(void)updateLatestModificationDate:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setDirty:(BOOL)arg1 ;
-(CKNotificationInfo *)notificationInfo;
-(NSString *)subscriptionID;
-(NSString *)recordType;
-(unsigned long long)subscriptionOptions;
-(void)_setupSubscription;
-(BOOL)isDirty;
-(CKDatabase *)database;
@end

