/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotUser.h>

@class NSMutableArray, PTHTweetbotRelationship;

@interface PTHTweetbotOtherUser : PTHTweetbotUser {

	NSMutableArray* _updateRelationshipBlocks;
	PTHTweetbotRelationship* _relationship;

}

@property (nonatomic,readonly) PTHTweetbotRelationship * relationship;              //@synthesize relationship=_relationship - In the implementation block
-(id)initWithAccount:(id)arg1 tid:(long long)arg2 ;
-(id)mentionsCursor;
-(void)reportSpam:(/*^block*/id)arg1 ;
-(void)enableRetweets:(/*^block*/id)arg1 ;
-(void)disableRetweets:(/*^block*/id)arg1 ;
-(void)updateRelationship:(/*^block*/id)arg1 ;
-(void)updateRelationshipIfNeeded:(/*^block*/id)arg1 ;
-(void)block:(/*^block*/id)arg1 ;
-(void)unblock:(/*^block*/id)arg1 ;
-(void)follow:(/*^block*/id)arg1 ;
-(void)unfollow:(/*^block*/id)arg1 ;
-(PTHTweetbotRelationship *)relationship;
-(void)setAccount:(id)arg1 ;
@end

