/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotAccountDataMonitor.h>

@class NSDate, NSArray, NSDictionary;

@interface PTHTweetbotAccountDataStatisticsMonitor : PTHTweetbotAccountDataMonitor {

	NSDate* _lastLookupDate;
	BOOL _isUpdatingRecentStatuses;
	BOOL _isUpdatingRecentFollowers;
	BOOL _isUpdatingRecentDailyInteractionCounts;
	NSArray* _recentStatuses;
	NSDictionary* _recentDailyInteractionCounts;
	NSArray* _recentFollowers;

}

@property (nonatomic,copy) NSArray * recentStatuses;                                 //@synthesize recentStatuses=_recentStatuses - In the implementation block
@property (nonatomic,copy) NSDictionary * recentDailyInteractionCounts;              //@synthesize recentDailyInteractionCounts=_recentDailyInteractionCounts - In the implementation block
@property (nonatomic,copy) NSArray * recentFollowers;                                //@synthesize recentFollowers=_recentFollowers - In the implementation block
-(void)setRecentDailyInteractionCounts:(NSDictionary *)arg1 ;
-(NSDictionary *)recentDailyInteractionCounts;
-(NSArray *)recentStatuses;
-(id)initWithAccountData:(id)arg1 ;
-(void)update:(BOOL)arg1 streamed:(BOOL)arg2 ;
-(void)setRecentStatuses:(NSArray *)arg1 ;
-(void)setRecentFollowers:(NSArray *)arg1 ;
-(void)_updateRecentStatuses:(BOOL)arg1 ;
-(void)_updateRecentDailyInteractionCounts;
-(void)_updateRecentFollowers;
-(NSArray *)recentFollowers;
-(id)init;
-(void)_sendDidChange;
@end

