/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


#import <Tweetbot/Tweetbot-Structs.h>
@class NSMutableSet, NSDate, NSTimer;

@interface PTHTweetbotSyncTweetMarkerPositionController : NSObject {

	NSMutableSet* _dirtyCursors;
	NSDate* _nextPollDate;
	BOOL _isPolling;
	BOOL _isPosting;
	NSTimer* _postTimer;

}
+(id)sharedController;
-(void)_post;
-(void)markCursorSynced:(id)arg1 ;
-(long long)lastReadTIDForCursor:(id)arg1 ;
-(SCD_Struct_PT3)pendingSyncPositionForCursor:(id)arg1 ;
-(void)_pollIfNeeded;
-(void)_poll;
-(void)_cursorWasScrolled:(id)arg1 ;
-(SCD_Struct_PT3)pendingSyncPositionForCursorUniqueID:(id)arg1 ;
-(void)setPendingSyncPosition:(SCD_Struct_PT3)arg1 forCursorUniqueID:(id)arg2 ;
-(id)cursorToCollectionName:(id)arg1 ;
-(id)queryDictionaryForAccount:(id)arg1 ;
-(long long)syncVersionForCollectionName:(id)arg1 ;
-(id)collectionNameToUniqueID:(id)arg1 account:(id)arg2 ;
-(void)setSyncVersion:(long long)arg1 forCollectionName:(id)arg2 ;
-(void)dealloc;
-(id)init;
-(id)request;
@end

