/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotProfileChildController.h>

@class UIButton;

@interface PTHTweetbotProfileRelationshipsController : PTHTweetbotProfileChildController {

	UIButton* _followersButton;
	UIButton* _followingButton;
	long long _followersCount;
	long long _followingCount;

}
-(id)initWithTweetbotUser:(id)arg1 ;
-(void)_showFollowers:(id)arg1 ;
-(void)_showFollowing:(id)arg1 ;
-(void)userWasUpdated;
-(void)loadView;
-(void)_updateTitles;
@end

