/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotStatusCursorController.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@class PTHTweetbotUser, NSString;

@interface PTHTweetbotMentionsController : PTHTweetbotStatusCursorController <UIGestureRecognizerDelegate> {

	PTHTweetbotUser* _tweetbotUser;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithTweetbotUser:(id)arg1 ;
-(id)searchTitle;
-(id)nothingFoundTitle;
-(void)_updateUnreadTab;
-(void)_playNewItemsSoundIfNeeded;
-(BOOL)shouldShowPushNotification:(id)arg1 ;
-(unsigned long long)separatorStyleTop:(id)arg1 bottom:(id)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(id)reuseIdentifier;
-(void)viewDidAppear:(BOOL)arg1 ;
@end

