/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <UIKit/UITableViewCell.h>

@class PTHTweetbotStatisticsStatusView, UIViewController, PTHTweetbotStatus;

@interface PTHTweetbotStatisticsStatusCell : UITableViewCell {

	PTHTweetbotStatisticsStatusView* _statusView;

}

@property (assign,nonatomic,__weak) UIViewController * viewController; 
@property (nonatomic,retain) PTHTweetbotStatus * status; 
@property (assign,nonatomic) unsigned long long maximumFavorites; 
@property (assign,nonatomic) unsigned long long maximumRetweets; 
@property (assign,nonatomic) unsigned long long topSeparatorStyle; 
+(double)cellHeightWithStatus:(id)arg1 forTableView:(id)arg2 ;
-(void)setMaximumFavorites:(unsigned long long)arg1 ;
-(unsigned long long)maximumFavorites;
-(void)setMaximumRetweets:(unsigned long long)arg1 ;
-(unsigned long long)maximumRetweets;
-(void)setTopSeparatorStyle:(unsigned long long)arg1 ;
-(unsigned long long)topSeparatorStyle;
-(void)layoutSubviews;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2 ;
-(UIEdgeInsets)layoutMargins;
-(void)setViewController:(UIViewController *)arg1 ;
-(UIViewController *)viewController;
-(PTHTweetbotStatus *)status;
-(void)setStatus:(PTHTweetbotStatus *)arg1 ;
@end

