/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <UIKit/UIView.h>

@class PTHShapeView, NSArray, UIFont;

@interface PTHTweetbotStatisticsHeaderGraphView : UIView {

	PTHShapeView* _backgroundView;
	PTHShapeView* _strokeView;
	PTHShapeView* _fillView;
	NSArray* _dayLabels;
	CGPoint _points[7];
	NSArray* _recentDailyFollowCounts;
	UIFont* _dayLabelFont;

}

@property (nonatomic,retain) NSArray * recentDailyFollowCounts;              //@synthesize recentDailyFollowCounts=_recentDailyFollowCounts - In the implementation block
@property (nonatomic,retain) UIFont * dayLabelFont;                          //@synthesize dayLabelFont=_dayLabelFont - In the implementation block
@property (nonatomic,readonly) CGPoint* points; 
-(void)setDayLabelFont:(UIFont *)arg1 ;
-(void)setRecentDailyFollowCounts:(NSArray *)arg1 ;
-(void)_updateDayLabels;
-(NSArray *)recentDailyFollowCounts;
-(UIFont *)dayLabelFont;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)_update;
-(id)viewForLastBaselineLayout;
-(CGPoint*)points;
@end

