/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotProfileChildController.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@class PTHTweetbotCursor, NSString;

@interface PTHTweetbotProfileRecentTweetsController : PTHTweetbotProfileChildController <UIGestureRecognizerDelegate> {

	PTHTweetbotCursor* _userTimelineCursor;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithTweetbotUser:(id)arg1 ;
-(id)initWithUserTimelineCursor:(id)arg1 ;
-(void)swipeLeft:(id)arg1 ;
-(void)_loadStatuses:(id)arg1 ;
-(void)showTweet:(id)arg1 ;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(void)loadView;
@end

