/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/Tweetbot-Structs.h>
#import <Tweetbot/PTHTweetbotAccountTabBar.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <Tweetbot/PTHTweetbotAccountPickerViewDelegate.h>

@class UIScrollView, PTHTweetbotCurrentUser, NSString;

@interface PTHTweetbotAccountRegularTabBar : PTHTweetbotAccountTabBar <UIGestureRecognizerDelegate, PTHTweetbotAccountPickerViewDelegate> {

	UIScrollView* _scrollView;
	PTHTweetbotCurrentUser* _user;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithAccount:(id)arg1 controllers:(id)arg2 ;
-(id)colorGroupName;
-(void)layoutSubviews;
-(CGSize)intrinsicContentSize;
@end

