/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <PTHCommon/PTHViewController.h>

@class UIViewController, UIImageView, PTHTweetbotAccountController, PTHTweetbotAccount;

@interface PTHTweetbotMainController : PTHViewController {

	UIViewController* _childController;
	UIImageView* _launchIconView;
	PTHTweetbotAccountController* _selectedAccountController;

}

@property (nonatomic,__weak,readonly) UIViewController * currentViewController; 
@property (nonatomic,readonly) PTHTweetbotAccountController * selectedAccountController;              //@synthesize selectedAccountController=_selectedAccountController - In the implementation block
@property (nonatomic,__weak,readonly) PTHTweetbotAccount * selectedAccount; 
+(id)mainController;
+(void)playNewItemsSound;
+(void)unmuteNewItemsSound;
+(void)muteNewItemsSound;
+(void)initialize;
-(void)launch:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(PTHTweetbotAccountController *)selectedAccountController;
-(PTHTweetbotAccount *)selectedAccount;
-(void)setSelectedAccount:(id)arg1 selectedTab:(long long)arg2 animation:(long long)arg3 completion:(/*^block*/id)arg4 ;
-(BOOL)shouldShowPushNotification:(id)arg1 ;
-(void)showSetupController:(long long)arg1 completion:(/*^block*/id)arg2 ;
-(void)_hideSetupController:(/*^block*/id)arg1 ;
-(void)_setSelectedAccount:(id)arg1 selectedTab:(long long)arg2 animation:(long long)arg3 completion:(/*^block*/id)arg4 ;
-(UIViewController *)currentViewController;
-(BOOL)prefersStatusBarHidden;
-(long long)preferredStatusBarUpdateAnimation;
-(unsigned long long)supportedInterfaceOrientations;
-(void)reset;
-(BOOL)shouldAutorotate;
-(void)loadView;
-(id)childViewControllerForStatusBarStyle;
-(id)childViewControllerForStatusBarHidden;
@end

