/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <PTHCommon/PTHViewController.h>

@class PTHTweetbotAccount, PTHStaticOptionsSectionView, PTHStaticSectionView, PTHStaticSectionCell, NSDateFormatter;

@interface PTHTweetbotPushSettingsController : PTHViewController {

	PTHTweetbotAccount* _account;
	PTHStaticOptionsSectionView* _mentionsSection;
	PTHStaticSectionView* _notificationsSection;
	PTHStaticSectionCell* _lastNotificationCell;
	PTHStaticSectionCell* _requestTestCell;
	long long _lastPushTypes;
	BOOL _needsSettings;
	BOOL _syncedSettings;
	NSDateFormatter* _dateFormatter;

}
-(void)_didBecomeActive;
-(void)_didEnterBackground;
-(id)_dateFromMinute:(unsigned long long)arg1 ;
-(void)changePushOption;
-(void)_testPush:(id)arg1 ;
-(void)_showMessage:(id)arg1 actionURL:(id)arg2 ;
-(id)_stringFromMinute:(unsigned long long)arg1 ;
-(unsigned long long)_minuteFromDate:(id)arg1 ;
-(void)_updateDisplay;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)_updateSettings;
-(id)initWithAccount:(id)arg1 ;
@end

