/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Tweetbot/PTHTweetbotStatusDetailChildController.h>

@class NSMutableArray, UIStackView, UILabel, UIView, UILayoutGuide, NSArray, NSLayoutYAxisAnchor;

@interface PTHTweetbotStatusDetailConversationController : PTHTweetbotStatusDetailChildController {

	NSMutableArray* _statusViews;
	UIStackView* _stackView;
	UILabel* _inReplyToLabel;
	UIView* _inReplyToView;
	UILayoutGuide* _topAnchorLayoutGuide;
	NSArray* _conversationStatuses;

}

@property (nonatomic,readonly) NSArray * conversationStatuses;               //@synthesize conversationStatuses=_conversationStatuses - In the implementation block
@property (nonatomic,readonly) NSLayoutYAxisAnchor * topAnchor; 
@property (nonatomic,readonly) UIView * lastStatusView; 
-(void)swipeLeft:(id)arg1 ;
-(void)_updateReplyToLabel;
-(void)statusWasUpdated;
-(void)_loadConversation;
-(UIView *)lastStatusView;
-(NSArray *)conversationStatuses;
-(void)previewingStatusDidChange;
-(void)loadView;
-(NSLayoutYAxisAnchor *)topAnchor;
@end

