/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@class PTHTweetbotAccount, NSDictionary;

@interface PTHTweetbotService : NSObject {

	PTHTweetbotAccount* _account;
	NSDictionary* _authenticationInfo;

}
+(id)serviceClasses;
+(id)authenticationInfoForAccount:(id)arg1 ;
+(id)customInfoForAccount:(id)arg1 ;
+(void)saveAuthenticationInfo:(id)arg1 forAccount:(id)arg2 ;
+(void)authenticate:(id)arg1 completion:(/*^block*/id)arg2 ;
+(void)setCustomInfo:(id)arg1 forAccount:(id)arg2 ;
+(BOOL)verifyWithAccount:(id)arg1 ;
+(id)authenticationFailureTweetbotError;
+(id)genericServiceFailureTweetbotError;
+(id)busyServiceFailureTweetbotError;
+(id)keychainServiceName;
+(id)keychainItemForAccount:(id)arg1 ;
+(id)_customInfoKeyForAccount:(id)arg1 ;
+(BOOL)isAvailable;
+(id)title;
+(id)defaultOptions;
+(BOOL)needsAuthentication;
-(id)customInfo;
-(id)authenticationInfo;
-(id)password;
-(id)initWithAccount:(id)arg1 ;
-(id)username;
@end

