/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:46 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

typedef struct CGPoint {
	double x;
	double y;
} CGPoint;

typedef struct CGSize {
	double width;
	double height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct {
	long long tid;
	double offset;
	double height;
} SCD_Struct_PT3;

typedef struct {
	CGPoint center;
	CGPoint span;
} SCD_Struct_PT4;

typedef struct _NSZone* NSZoneRef;

typedef struct __CTFont* CTFontRef;

typedef struct UIOffset {
	double horizontal;
	double vertical;
} UIOffset;

typedef struct NSRange {
	unsigned long long location;
	unsigned long long length;
} NSRange;

typedef struct sqlite3_stmt* sqlite3_stmtRef;

