/*
* This header is generated by classdump-dyld 0.7
* on Friday, December 11, 2015 at 5:59:45 PM Japan Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/3DB75626-9455-48D4-9D8D-D8CCA0F8B599/Tweetbot.app/Tweetbot
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@protocol UIActivityItemSource <NSObject>
@optional
-(id)activityViewController:(id)arg1 subjectForActivityType:(id)arg2;
-(id)activityViewController:(id)arg1 dataTypeIdentifierForActivityType:(id)arg2;
-(id)activityViewController:(id)arg1 thumbnailImageForActivityType:(id)arg2 suggestedSize:(CGSize)arg3;

@required
-(id)activityViewControllerPlaceholderItem:(id)arg1;
-(id)activityViewController:(id)arg1 itemForActivityType:(id)arg2;

@end

